name: 'Create artifact tag'

description: 'Outputs a string value for use as an artifact tag'

branding:
  icon: 'tag'
  color: 'white'

outputs:
  tag:
    description: 'Artifact tag'
    value: ${{ steps.artifact-tag-generator.outputs.tag }}

runs:
  using: "composite"
  steps:
    - id: artifact-tag-generator
      shell: bash
      run: |
        set -euxo pipefail
        
        echo "GITHUB_REF: $GITHUB_REF"
        echo "GITHUB_SHA: $GITHUB_SHA"
        
        if [ ${{ github.event_name }} = "release" ]
        then
          GIT_TAG_ONLY=$(echo $GITHUB_REF | sed "s|refs/tags/||")
          TAG="${GIT_TAG_ONLY}"
        
        else
          GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-8)
          TAG="${{ github.run_number }}-${GITHUB_SHA_SHORT}"
        fi
        
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        
